/aruco_node:
  ros__parameters:
    marker_size: 0.0254
    aruco_dictionary_id: DICT_4X4_1000
    image_topic: /image_raw
    camera_info_topic: /camera_info
    aruco_image_topic: /aruco_image_small
    aruco_poses_topic: /aruco_poses_small
    aruco_link_name: aruco_link_small
